import { ReconciliationResultSchema, type Artifact, type CanonicalStatus, type ClaimEvent, type ReconciliationResult } from "@/lib/schemas";

/** ClaimClarity prototype evidence normalization, not an official EPFO status mapping. */
export const STATUS_NORMALIZATION: Array<[RegExp, CanonicalStatus]> = [[/credit|amount.*received|bank.*received/i, "CREDITED"], [/reject|denied|not approved/i, "REJECTED"], [/settled|payment.*made|disburs/i, "SETTLED"], [/approved|sanction/i, "APPROVED"], [/process|pending|verification/i, "PROCESSING"], [/submit|received|portal/i, "SUBMITTED"]];
export function normalizeStatus(value: string | null | undefined): CanonicalStatus { return STATUS_NORMALIZATION.find(([pattern]) => pattern.test(value || ""))?.[1] ?? "UNKNOWN"; }
const ranks: Record<CanonicalStatus, number> = { UNKNOWN: 0, SUBMITTED: 1, PROCESSING: 2, APPROVED: 3, SETTLED: 4, REJECTED: 5, CREDITED: 6 };
const sortEvents = (events: ClaimEvent[]) => [...events].sort((a, b) => (a.date || "9999-12-31").localeCompare(b.date || "9999-12-31"));

export function reconcileClaim(artifacts: Artifact[], memberName: string | null, analysisMode: "demo" | "gemini"): ReconciliationResult {
  const events = sortEvents(artifacts.map(a => ({ artifactId: a.id, source: a.source, date: a.date, rawStatus: a.status, normalizedState: normalizeStatus(a.status || a.text), detail: a.text, ambiguity: a.ambiguity })));
  const ids = [...new Set(artifacts.map(a => a.claimId).filter((id): id is string => Boolean(id)))];
  const identity = { claimId: ids.length === 1 ? ids[0] : null, claimType: artifacts.map(a => a.claimType).find(Boolean) || null, amount: artifacts.map(a => a.amount).find(Boolean) || null };
  const known = events.filter(event => event.normalizedState !== "UNKNOWN");
  const uncertainties = artifacts.flatMap(a => a.ambiguity ? [a.ambiguity] : []).concat(!identity.claimId ? ["No reliable claim ID was found in the evidence."] : []);
  if (known.length < 2 || !events.some(e => e.date)) return ReconciliationResultSchema.parse({ claimIdentity: identity, memberName, events, conflicts: [], bestSupportedState: "UNKNOWN", confidence: "low", reasons: ["Not enough evidence to establish a reliable current state."], recommendedAction: "Add another dated claim record, notification, or outcome.", doNotDo: "Do not submit another claim based on this vague or incomplete evidence.", uncertainties, ruleFired: "INSUFFICIENT_EVIDENCE_REFUSAL", evidenceCount: artifacts.length, analysisMode });
  const conflicts: ReconciliationResult["conflicts"] = [];
  if (ids.length > 1) conflicts.push({ type: "IDENTIFIER_MISMATCH", message: "The supplied evidence contains different claim identifiers, so it may not all relate to one claim.", artifactIds: artifacts.filter(a => a.claimId).map(a => a.id) });
  const stages = [...new Set(known.map(e => e.normalizedState))];
  if (stages.length > 1) conflicts.push({ type: "DIFFERENT_STAGES", message: "These records appear to refer to the same claim, but they report different stages. That does not necessarily mean one record is wrong; the evidence does not form one clear citizen-facing state.", artifactIds: known.map(e => e.artifactId) });
  const terminal = known.filter(e => e.normalizedState === "CREDITED" || e.normalizedState === "SETTLED").at(-1);
  if (terminal && known.some(e => (e.normalizedState === "SUBMITTED" || e.normalizedState === "PROCESSING") && e.date && terminal.date && e.date < terminal.date)) conflicts.push({ type: "STALE_OBSERVATION", message: "The later settlement or credit evidence is stronger than the older processing signal in this synthetic case.", artifactIds: [terminal.artifactId, ...known.filter(e => (e.normalizedState === "SUBMITTED" || e.normalizedState === "PROCESSING") && e.date && terminal.date && e.date < terminal.date).map(e => e.artifactId)] });
  const best = known.some(e => e.normalizedState === "CREDITED") ? "CREDITED" : known.some(e => e.normalizedState === "SETTLED") ? "SETTLED" : known.reduce((best, e) => ranks[e.normalizedState] > ranks[best] ? e.normalizedState : best, "UNKNOWN" as CanonicalStatus);
  const primaryProcessing = best === "PROCESSING";
  const reasons = primaryProcessing ? ["Based on the evidence provided, processing appears to have started, but the supplied records do not establish final settlement."] : best === "CREDITED" ? ["Based on the evidence provided, later synthetic bank credit is the strongest completion signal."] : best === "SETTLED" ? ["Based on the evidence provided, later settlement evidence is stronger than earlier processing evidence."] : [`Evidence indicates ${best.toLowerCase()} as the best-supported prototype state.`];
  const confidence = conflicts.some(c => c.type === "IDENTIFIER_MISMATCH") ? "low" : primaryProcessing && conflicts.length ? "medium" : "high";
  const recommendedAction = primaryProcessing ? "Wait and monitor the existing claim rather than submitting a duplicate request." : best === "CREDITED" || best === "SETTLED" ? "Verify the settlement or credit in the supplied records; no duplicate claim is justified." : best === "REJECTED" ? "Review the supplied rejection record through the official channel before taking a corrective step." : "Monitor the existing evidence before taking another action.";
  const doNotDo = primaryProcessing ? "Don't submit another claim just because one source still shows an older or incomplete state." : best === "CREDITED" || best === "SETTLED" ? "Do not file a duplicate claim; the supplied evidence already indicates completion." : "Do not submit a duplicate claim until you have clearer evidence about the existing request.";
  return ReconciliationResultSchema.parse({ claimIdentity: identity, memberName, events, conflicts, bestSupportedState: best, confidence, reasons, recommendedAction, doNotDo, uncertainties, ruleFired: best === "CREDITED" ? "LATER_CREDIT_EVIDENCE_WINS" : best === "SETTLED" ? "LATER_SETTLEMENT_EVIDENCE_WINS" : "PROCESSING_SIGNALS_RECONCILED", evidenceCount: artifacts.length, analysisMode });
}
